### ISSUE TITLE
Which features are planned?

### ISSUE THREAD

**Issue by froschdesign** [nusphere/phpstorm-laminas-plugin#1]
Which features are planned for the plugin and can we help?

Maybe the following links are helpful:

- https://docs.mezzio.dev/mezzio/v3/reference/cli-tooling/
- https://github.com/orgs/laminas/projects/17

**Comment by jrcii** [comment]
My #1 pain with PhpStorm and laminas is that PhpStorm cannot infer usage references/links between the laminas-route action tokens and the controller action methods. You have to manually create them and keep them in sync:

```
        'example_route_foo'         => [
            'type'    => HttpRoute\Literal::class,
            'options' => [
                'route'    => '/foo/bar',
                'defaults' => [
                    'controller' => Controller\Foo\Bar::class,
                    /** @see \Application\Controller\Foo\Bar::bazAction */
                    'action' => 'baz',
                ],
            ],
        ],
```

I started making a plugin one day to fix this but I haven't been able to find the time.

**Comment by froschdesign** [comment]
With laminas-mvc-middleware you do not have this problem. 😉 

https://docs.laminas.dev/laminas-mvc-middleware/v2/quick-start/#mapping-routes-to-middleware-and-request-handlers
